name: "Build"
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2.3.4
      - name: install nix
        uses: cachix/install-nix-action@v13
      - name: download dataset
        run: nix-shell --run "cuticle_analysis --download-dataset"
      - name: run tests
        run: nix-shell --run "coverage run --source=cuticle_analysis --module pytest --verbose tests"
      - name: coverage report
        run: nix-shell --run "coverage xml"
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
